database connect successful Version:5.5.53
+++++++++++++++++++++++++++++++++++
开始验证proxy表中的数据
+++++++++++++++++++++++++++++++++++
开始爬虫进程
www.66ip.cn开始爬取
www.89ip.cn开始爬取
www.kuaidaili.com开始爬取
0
1
521保护绕过失败。网站地址为->www.66ip.cn
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/wangzeqing/Desktop/python/玩玩/bilibili/proxydatas/crawler/crawler.py", line 88, in http_open
    dbinstall(data,urllist)
UnboundLocalError: local variable 'data' referenced before assignment

成功清除重复id220154
Traceback (most recent call last):
  File "tables_keep.py", line 15, in <module>
    crawler('proxy',dbcon)
  File "/Users/wangzeqing/Desktop/python/玩玩/bilibili/proxydatas/crawler/crawler.py", line 44, in crawler
    t.start()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 741, in start
    self.__started.wait()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
